### ISSUE TITLE
Questions about sampling state from current belief details.

### ISSUE THREAD

**Issue by AaronAnima** [xavierpuigf/watch_and_help#4]
Hi, I'm really interested in your works. Recently, I tried to understand the details of Alice's policy by reading your code. However, due to the lack of annotations in the code, I still have some problems:

1. When testing an hp agent, how to initialize the belief? Is it initialized by the ground truth meta-data across all the rooms in the dataset?

2. How does belief initialize unseen node's position and rotation e.t.c.? Intuitively, belief should only initialize edges. But it seems that each node in belief.sampled_state['nodes'] has 'position' and 'rotation' attributes.

**Comment by xavierpuigf** [comment]
Hi @AaronAnima, sorry for the lack of details. Will be adding more comments on the code shortly. To answer your questions specifically:

1. The belief is initialized so that objects have a uniform prior over which room they could be in and also whether on which container they are or whether they are in a container at all. You can find the initialization for containers here:
https://github.com/xavierpuigf/watch_and_help/blob/main/agents/belief.py#L212
And the initialization for rooms here:
https://github.com/xavierpuigf/watch_and_help/blob/main/agents/belief.py#L232

2. We do not care about the object position and rotation, the nodes do indeed have position and rotation that come from the ground truth, but given that the planner is only using edges and states to do the planning, those attributes are ignored. It would be a nice extension to think about a spatial belief that also initialized those attributes, for better planning.

**Comment by AaronAnima** [comment]
Got it! Many thanks :)
